config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: 'users/registrations'
  }

  # アカウント設定表示用
  get 'users/account_show'
  get 'users/profile_show'
  get 'users/profile_edit'
  patch 'users/profile_show', to: 'users#update'

  # Room用
  get 'rooms/home'
  get 'rooms/result'
  get 'rooms/search'
  resources :rooms

  # Reservation用
  post 'reservations/confirmation', to: 'reservations#confirmation'
  resources :reservations
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :username, presence: true
  validates :introduction, length: { maximum: 200}
  
  # 使用するUploader
  mount_uploader :avatar, AvatarUploader

  has_many :rooms
  has_many :reservations

  # attr_writer :login
  # validates :username, presence: true, uniqueness: { case_sensitive: false }
  # validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true
  # validate :validate_username

  # def login
  #   @login || self.username || self.email
  # end

  # def self.find_for_database_authentication(warden_conditions)
  #   conditions = warden_conditions.dup
  #   if (login = conditions.delete(:login))
  #     where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
  #   elsif conditions.has_key?(:username) || conditions.has_key?(:email)
  #     where(conditions.to_h).first
  #   end
  # end

  # def validate_username
  #   if User.where(email: username).exists?
  #     errors.add(:username, :invalid)
  #   end
  # end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def account
  end

  def profile
  end

  def profile_edit
    @user = User.find(current_user.id)
  end

  def update
    @user = current_user
    if @user.update(params.permit(:avatar, :username, :introduction))
      redirecto_to '/user/profile'
    else
      render '/user/profile_edit'
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]
  # before_action :configure_profile_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password, :password_confirmation])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar, :username, :introduction])
  end

  # def configure_profile_update_params
  #   binding.pry
  #   devise_parameter_sanitizer.permit(:profile_update, keys: [:avatar, :username, :introduction])
  # end

  protected

  # アカウント更新
  def after_update_path_for(resource)
    '/rooms/home'
  end

  # 新規登録
  def after_sign_up_path_for(resource)
    '/rooms/home'
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  #ログイン後のリダイレクト先
  def after_sign_in_path_for(resource)
    flash[:notice] = "ログインに成功しました"
    '/rooms/home'
  end 
  #ログアウト後のリダイレクト先
  def after_sign_out_path_for(resource)
    flash[:notice] = "ログアウトしました"
    '/rooms/home'
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def account_show
  end

  def profile_show
  end

  def profile_edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to '/users/profile_show'
    else
      render '/user/profile_edit'
    end
  end

  def user_params
    params.require(:user).permit(:avatar, :username, :introduction)
  end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/account_show.erb
<section class="container UserSection">
  <h2>設定</h2>
  <div class="UserContainer">
    <ul class="SideNavigation">
      <li class="SideNavigation__item active">
        <a href="/users/account_show">アカウント</a>
      </li>

      <li class="SideNavigation__item ">
        <a href="/users/profile_show">プロフィール</a>
      </li>
    </ul>

    <div class="AccountInformation">
      <ul class="TabNavigation">
        <li class="TabNavigation__item active">
        <a href="/users/account_show">アカウント</a></li>

        <li class="TabNavigation__item ">
        <a href="/users/profile_show">プロフィール</a></li>
      </ul>

      <div class="AccountInformation__header">
        <h3>アカウント</h3>
        <a class="AccountInformation__link" href="/users/edit">
        <%= image_tag 'pencil_icon.png', width: '30', height: '30' %>編集</a>
      </div>

      <div class="AccountInformation__input-group">
        <label class="AccountInformation__label" for="email">メールアドレス</label>
        <p class="AccountInformation__value">
          <%= current_user.email%>
        </p>
      </div>

      <div class="AccountInformation__input-group">
        <label class="AccountInformation__label" for="password">パスワード</label>
        <p class="AccountInformation__value">
          ********
        </p>
      </div>
    </div>
  </div>
</section>

app/views/users/profile_edit.erb
<h2>プロフィール</h2>

<%= form_with model: @user, url: users_profile_show_path do |f| %>

  <div class="field">
    <%= f.label :画像アップロード %><br />
    <%= image_tag @user.avatar.url, class:'UserIcon', width: '70', height: '70' %>
    <%= f.file_field :avatar %>
  </div>

  <div class="field">
    <%= f.label :ユーザー名 %><br />
    <%= f.text_field :username %>
  </div>

  <div claa="field">
    <%= f.label :自己紹介 %><br />
    <%= f.text_area :introduction %>
  </div>

  <div class="actions">
    <%= f.submit "保存" %>
    <%= link_to "戻る", :back %><br/>
  </div>
<% end %>

app/views/users/profile_show.html.erb
<section class="container UserSection">
  <h2>設定</h2>
  <div class="UserContainer">
    <ul class="SideNavigation">
      <li class="SideNavigation__item ">
        <a href="/users/account_show">アカウント</a>
      </li>

      <li class="SideNavigation__item active">
        <a href="/users/profile_show">プロフィール</a>
      </li>
    </ul>

    <div class="AccountInformation">
      <ul class="TabNavigation">
          <li class="TabNavigation__item ">
          <a href="/users/account_show">アカウント</a>
        </li>

        <li class="TabNavigation__item active">
          <a href="/users/profile_show">プロフィール</a>
        </li>
      </ul>

      <div class="AccountInformation__header">
        <h3>プロフィール</h3>
        <a class="AccountInformation__link" href="/users/profile_edit">
          <%= image_tag 'pencil_icon.png', width: '30', height: '30' %>編集
        </a>
      </div>

      <div class="AccountInformation__input-group">
        <label class="AccountInformation__label" for="image">アイコン画像</label>
        <p class="AccountInformation__value AccountInformation__value--image">
          <%= image_tag current_user.avatar.url, class:'UserIcon', size: "45x45" %>
        </p>
      </div>

      <div class="AccountInformation__input-group">
        <label class="AccountInformation__label" for="name">名前</label>
        <p class="AccountInformation__value">
          <%= current_user.username %>
        </p>
      </div>

      <div class="AccountInformation__input-group">
        <label class="AccountInformation__label" for="introduction">自己紹介</label>
        <p class="AccountInformation__value">
          <%= current_user.introduction %>
        </p>
      </div>
    </div>
  </div>
</section>