config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: 'users/registrations'
  }

  # アカウント設定表示用
  get 'users/account_show'
  get 'users/profile_show'
  get 'users/profile_edit'
  patch 'users/profile_show', to: 'users#update'

  # Room用
  get 'rooms/home'
  get 'rooms/result'
  get 'rooms/search'
  resources :rooms

  # Reservation用
  post 'reservations/confirmation', to: 'reservations#confirmation'
  resources :reservations
  
end

app/models/room.rb
class Room < ApplicationRecord

  belongs_to :user
  has_many :reservations

  # RoomImageアップローダーと紐付け
  mount_uploader :room_image, RoomImageUploader
  
  validates :room_name, presence: true
  validates :room_info, length: { in: 1..150 }
  validates :room_price, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}
  validates :room_address, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ["room_name", "room_info", "room_price", "room_address"]
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_q, only: [:home, :search, :result]

  # ホーム画面
  def home
  end

  def search
    @results = @q.result
  end

  # 検索語の結果を表示
  def result
    @results = @q.result
  end

  def index
    @rooms = current_user.rooms
  end

  def new
    @rooms = Room.new
  end

  def create
    @rooms = Room.new(params.require(:room).permit(:room_name, :room_info, :room_price, :room_address, :room_image))
    @rooms.user_id = current_user.id
    if @rooms.save
      redirect_to :rooms
    else
      render "new"
    end
  end

  def show
    @rooms = Room.find(params[:id])
    @reservations = Reservation.new
  end

  def edit
    @rooms = Room.find(params[:id])
  end

  def update
    @rooms = Room.find(params[:id])
    if @rooms.update(params.require(:room).permit(:room_name, :room_info, :room_price, :room_address, :room_image))
      redirect_to :rooms
    else
      render :edit
    end
  end

  def destroy
    @rooms = Room.find(params[:id])
    @rooms.destroy
    redirect_to :rooms
  end

  private
  def set_q
    @q = Room.ransack(params[:q])
  end

end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/edit.erb
<div class="form-view">
  <section class="form-container">
    <%= render "shared/error", obj: @rooms %>
    <h2>施設情報の編集</h2></br>
    <%= form_with model: @rooms do |r| %>
      <table class="form-table align-middle">
        
        <div class="room-form-input-group">
          <label class="roomform-label form-label"><%= r.label :施設名 %></label>
          <div class="roomform-input"><%= r.text_field :room_name, class:"input-textbox" %></div>
        </div>

        <div class="room-form-input-group">
          <label class="roomform-label form-label"><%= r.label :施設詳細 %></label>
          <div class="roomform-input"><%= r.text_area :room_info, class:"input-textarea" %></div>
        </div>

        <div class="room-form-input-group">
          <label class="roomform-label form-label"><%= r.label :料金 %></label>
          <div class="roomform-input"><%= r.text_field :room_price, class:"input-textbox" %></div>
        </div>

        <div class="room-form-input-group">
          <label class="roomform-label form-label"><%= r.label :住所 %></label>
          <div class="roomform-input"><%= r.text_field :room_address, class:"input-textbox" %></div>
        </div>

        <div class="room-form-input-group">
          <label class="roomform-label form-label"><%= r.label :施設画像 %></label>
          <div class="roomform-input"><%= r.file_field :room_image %></div>
        </div>

        <div class="form-button-group">
          <%= r.submit "保存" , class: "input-form-submit btn-block btn btn-large btn-primary" %>
        </div>

        <div class="form-button-group">
          <a><%= link_to "キャンセル", :back, class:"btn-block btn btn-outline-secondary cancel" %></a>
        </div>
        
      </table>
    <% end %>
  </section>
</div>

app/views/rooms/home.html.erb
<div class="FirstView">
  <section class="container">
    <h2 class="FirstViewTitle">
      Potepan Shareで<br>
      まだ体験したことのない<br>
      旅をしよう
    </h2>
    <div class="FirstViewSerch">
      <%= search_form_for @q, url: rooms_result_path do |f| %>
        <%= f.search_field :room_address_cont, class: 'form-control HomeSearch', placeholder: 'エリア名を入力' %>
        <%= f.submit '検索', class: 'Button FirstViewSerchButton' %>
      <% end %>
    </div>
  </section>
</div>

<div class="container">
  <section class="RecommendAreaSection">
    <h2 class="RecommendAreaTitle">おすすめのエリア</h2>
    <div class="RecommendAreas">
      <%= link_to image_tag("tokyo.jpg", size: "260x450" ), {:controller=>"rooms",:action=>"result",:q=>{:room_address_cont=>('東京')}}, class: "EachArea" %>
      <%= link_to image_tag("osaka.jpg", size: "260x450" ), {:controller=>"rooms",:action=>"result",:q=>{:room_address_cont=>('大阪')}}, class: "EachArea" %>
      <%= link_to image_tag("kyoto.jpg", size: "260x450" ), {:controller=>"rooms",:action=>"result",:q=>{:room_address_cont=>('京都')}}, class: "EachArea" %>
      <%= link_to image_tag("sapporo.jpg", size: "260x450" ), {:controller=>"rooms",:action=>"result",:q=>{:room_address_cont=>('札幌')}}, class: "EachArea" %>
    </div>
  </section>
</div>

app/views/rooms/index.erb
<section class="container room-list-container">
  <h2>登録済み一覧</h2>
  <div>
    <table class="table align-middle">
      <thead>
        <tr>
          <th>画像</th>
          <th>施設名</th>
          <th>紹介文</th>
          <th>料金</th>
          <th>作成日</th>
          <th></th>
        </tr>
      </thead>

      <tdoby>
        <% @rooms.each do |r| %>
          <tr>
            <th class="align-middle"><%= image_tag r.room_image.to_s, size: "150x100" %></th>
            <th class="align-middle"><%= link_to r.room_name, room_path(r) %></th>
            <th class="align-middle"><%= r.room_info %></th>
            <th class="align-middle">¥ <%= r.room_price %></th>
            <th class="align-middle"><%= r.created_at.to_s(:room_inded_date_jp) %></th>
            <th class="align-middle"><%= link_to "編集", edit_room_path(r) %></th>
            <th class="align-middle"><%= button_to "削除", room_path(r), { method: :delete, data: { confirm: '本当に削除しますか？' } } %></th>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</section>

app/views/rooms/new.erb
<div class="form-view">
  <section class="form-container">
    <%= render "shared/error", obj: @rooms %>
    <h2>新規登録</h2></br>
    <%= form_with model: @rooms do |r| %>
      <table class="form-table align-middle">
        
        <div class="room-form-input-group">
          <label class="roomform-label form-label"><%= r.label :施設名 %></label>
          <div class="roomform-input"><%= r.text_field :room_name, :placeholder => "ルーム名を入力", class:"input-textbox" %></div>
        </div>

        <div class="room-form-input-group">
          <label class="roomform-label form-label"><%= r.label :施設詳細 %></label>
          <div class="roomform-input"><%= r.text_area :room_info, :placeholder => "施設詳細を入力", class:"input-textarea" %></div>
        </div>

        <div class="room-form-input-group">
          <label class="roomform-label form-label"><%= r.label :料金 %></label>
          <div class="roomform-input"><%= r.text_field :room_price, :placeholder => "一日あたりの料金を入力", class:"input-textbox" %></div>
        </div>

        <div class="room-form-input-group">
          <label class="roomform-label form-label"><%= r.label :住所 %></label>
          <div class="roomform-input"><%= r.text_field :room_address, :placeholder => "住所を入力", class:"input-textbox" %></div>
        </div>

        <div class="room-form-input-group">
          <label class="roomform-label form-label"><%= r.label :施設画像 %></label>
          <div class="roomform-input"><%= r.file_field :room_image %></div>
        </div>

        <div class="form-button-group">
          <%= r.submit "保存" , class: "input-form-submit btn-block btn btn-large btn-primary" %>
        </div>

        <div class="form-button-group">
          <a><%= link_to "キャンセル", :back, class:"btn-block btn btn-outline-secondary cancel" %></a>
        </div>
        
      </table>
    <% end %>
  </section>
</div>

app/views/rooms/result.erb
<section class="SearchRoomsFormContainer">
    <form class="SearchRoomsForm">
      <%= search_form_for @q, url: rooms_result_path do |f| %>
        <div class="SearchRoomsForm__input-group--area">
        <%= f.search_field :room_address_cont, class: "SearchRoomsForm__input", placeholder: 'エリア名を入力' %>
        </div>
        <div>
          <%= f.search_field :room_info_cont, class: "SearchRoomsForm__input", placeholder: 'キーワード名を入力' %>
        </div>
        <%= f.submit '検索', class: "SearchRoomsForm__button Button FirstViewSerchButton" %>
      <%end%>
    </form>
</section>

<section class="RoomsContainer">
  <p class="RoomsContainer-result"><%= @results.count %> 件が見つかりました</p>
  <ul class="RoomList">
    <% @results.each do |r| %>
      <li class="Room">
        <%= image_tag r.room_image.to_s, class:"RoomImage" %>
        <div class="RoomBody">
          <p class="RoomName"><%= r.room_name %></p>
          <p class="RoomAddress"><%= r.room_address %></p>
          <p>☆ ☆ ☆ ☆ ☆</p>
          <p class="RoomInfo"><%= r.room_info %></p>
          <div class="RoomFooter">
            <p class="RoomPrice">¥<%= r.room_price %>〜</p>
            <a><%= link_to "詳細はこちら", room_path(r), class:"RoomLink" %></a>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
</section>

app/views/rooms/show.erb
<section class="RoomContainer">
  <div>
    <div class="LinksContainer">
      <%= link_to "戻る", :back %>
      <%= link_to "編集", edit_room_path(@rooms) %>
    </div>
    <div class="RoomDetails">
      <th><%= image_tag @rooms.room_image.to_s, size: "520x300" %></th>
      <div class="RoomTextContainer">
        <div class="RoomDetailsBody_name-and-price">
          <p class="Details-name"><%= @rooms.room_name %></p>
          <p class="Details-price">¥<%= @rooms.room_price%>〜</p>
        </div>
        <div>
          <p class="Details-address"><%= @rooms.room_address %></p>
          <p>☆ ☆ ☆ ☆ ☆</p>
        </div>
        <div>
          <p class="Details-info"><%= @rooms.room_info %></p>
        </div>
        <%= form_with model: @reservations, method: :post, url: reservations_confirmation_path do |r| %>
          <div class="reserve_form">
            <div>
              <%= r.label :チェックイン %>
              <%= r.date_field :check_in %>
            </div>
            <div>
              <%= r.label :チェックアウト %>
              <%= r.date_field :check_out %>
            </div>
            <div>
              <%= r.label :人数 %>
              <%= r.text_field :people, class:'people_form' %>
            </div>
            <div>
              <%= r.hidden_field :room_id, value: @rooms.id %>
              <%= r.submit '予約する', class: "SearchRoomsForm__button Button FirstViewSerchButton" %>
            </div>
          </div>
          <p class="validation-frame roon-new-validation room-reserve"><%= flash[:alert] %></p>
        <% end %>
      </div>
  </div>
</section>