config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: 'users/registrations'
  }

  # アカウント設定表示用
  get 'users/account_show'
  get 'users/profile_show'
  get 'users/profile_edit'
  patch 'users/profile_show', to: 'users#update'

  # Room用
  get 'rooms/home'
  get 'rooms/result'
  get 'rooms/search'
  resources :rooms

  # Reservation用
  post 'reservations/confirmation', to: 'reservations#confirmation'
  resources :reservations
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RoomReserveApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="Header">
      <section class="HeaderItems">
        <%= link_to image_tag("logo.png", width: "221px"), rooms_home_path %> 
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <div class="dropdown">
              <a class="dropdowntext" data-toggle="dropdown" role="button" aria-expanded="false">
                <%= image_tag current_user.avatar.url, class:'UserIcon', size: "45x45" %>
                <%= current_user.username %><span class="caret"></span>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li><a class="dropdown-item"><%= link_to "施設の新規登録", new_room_path %></a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item"><%= link_to "予約済み一覧", reservations_path %></a></li>
                <li><a class="dropdown-item"><%= link_to "登録済み一覧", rooms_path %></a></li>
                <li><a class="dropdown-item"><%= link_to "アカウント設定", users_account_show_path %></a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item"><%= button_to "ログアウト", destroy_user_session_path, method: :delete %></a></li>
              </ul>
            </div>
          <% else %>
            <li class="Navlogin"><%=link_to "ログイン", new_user_session_path %></li>
            <li><%=link_to "新規登録", new_user_registration_path , class:"btn btn-lg btn-primary" %></li>
          <% end %>
        </ul>
      </section>
    </header>
    <div>
      <%= yield %>
    </div>
    <footer class="Footer">
      <div class="FooterContainer">
        <%= link_to image_tag("logo.png", width: "292px"), rooms_home_path %>
        <p class="FooterText">Copyright © Potepan Share 2023 All rights reserved</p>
      </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  </body>
</html>